name: Build caddy

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - path: 'windows/amd64'
            os: 'windows'
            arch: 'amd64'
            variant: ''
          - path: 'linux/amd64'
            os: 'linux'
            arch: 'amd64'
            variant: ''
          - path: 'linux/arm64/v8'
            os: 'linux'
            arch: 'arm64'
            variant: '8'
          - path: 'linux/arm/v7'
            os: 'linux'
            arch: 'arm'
            variant: '7'
          - path: 'linux/arm/v6'
            os: 'linux'
            arch: 'arm'
            variant: '6'
    steps:
      - name: Set up Golang environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Set up xcaddy
        run: |-
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: Build caddy
        env:
          GOOS: ${{matrix.os}}
          GOARCH: ${{matrix.arch}}
          GOARM: ${{matrix.variant}}
        run: |-
          xcaddy build --output ./build/${{matrix.path}}/caddy \
            --with github.com/lucaslorentz/caddy-docker-proxy/plugin \
            --with github.com/abiosoft/caddy-exec \
            --with github.com/greenpau/caddy-auth-portal \
            --with github.com/greenpau/caddy-authorize \
            --with github.com/caddy-dns/duckdns
