name: Build and push

on:
  workflow_dispatch:
  push:
    tags: 
      - latest

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository_owner}}/caddy

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.4.1'

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{env.REGISTRY}}
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build caddy multiplatform
        id: build-caddy
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{env.IMAGE_NAME}}:latest

      - name: Test build
        id: test
        run: |
          

      - name: Build and push docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,windows/amd64
          push: true
          tags: ${{env.IMAGE_NAME}}:latest

      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ${{env.REGISTRY}}/${{env.IMAGE_NAME}}@${{steps.build-caddy.outputs.digest}}
