name: Build and push docker images

on:
  workflow_dispatch:
  repository_dispatch:

env:
  REGISTRY: ghcr.io
  USERNAME: ${{github.actor}}
  PASSWORD: ${{secrets.GITHUB_TOKEN}}
  IMAGE_NAME: ${{github.repository_owner}}/caddy

jobs:
  caddy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - platform: 'windows/amd64'
            os: 'windows'
            arch: 'amd64'
            variant: ''
          - platform: 'linux/amd64'
            os: 'linux'
            arch: 'amd64'
            variant: ''
          - platform: 'linux/arm64'
            os: 'linux'
            arch: 'arm64'
            variant: ''
          - platform: 'linux/arm/v7'
            os: 'linux'
            arch: 'arm'
            variant: '7'
          - platform: 'linux/arm/v6'
            os: 'linux'
            arch: 'arm'
            variant: '6'
    steps:
      - name: Set up Golang environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Set up xcaddy
        run: |-
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: Build caddy
        env:
          GOOS: ${{matrix.os}}
          GOARCH: ${{matrix.arch}}
          GOARM: ${{matrix.variant}}
        run: |-
          xcaddy build --output ./build/${{matrix.platform}}/caddy \
            --with github.com/lucaslorentz/caddy-docker-proxy/plugin \
            --with github.com/abiosoft/caddy-exec \
            --with github.com/greenpau/caddy-auth-portal \
            --with github.com/greenpau/caddy-authorize \
            --with github.com/caddy-dns/duckdns
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  docker:
    needs: caddy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - run: ls -lR

      - name: Test if an update is needed
        run: |
          chmod 700 ./build/linux/amd64/caddy
          ./build/linux/amd64/caddy list-modules -packages -versions > ./list-modules.txt
          ! git diff --exit-code list-modules.txt

      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.4.1'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log into registry ${{env.REGISTRY}}
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{env.USERNAME}}
          password: ${{env.PASSWORD}}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: windows/amd64,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{env.IMAGE_NAME}}:latest

      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest

      - name: Push repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic build 
          branch: master
          file_pattern: list-modules.txt
