name: Test

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test if an update is needed
        run: |
          chmod 700 ./build/linux/amd64/caddy
          ./build/linux/amd64/caddy list-modules -packages -versions > ./list-modules.txt
          ! git diff --exit-code list-modules.txt

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push docker image (linux)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/syp1975/caddy:latest

      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ghcr.io/syp1975/caddy:latest

      - name: Push repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic build 
          branch: master
          file_pattern: list-modules.txt
